### ISSUE TITLE
`[[_TOC_]]` isn't removed if it came from a snippet

### ISSUE THREAD

**Issue by DetachHead** [daxartio/mkdocs-gitlab#1]
if you import a markdown file that contains a `[[_TOC_]]` using [snippet syntax](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/), it doesn't get removed
```md
<!-- ./docs/index.md -->
--8<-- "README.md"
```
```md
<!-- ./README.md -->
[[_TOC_]]
```
```yaml
# ./mkdocs.yml
markdown_extensions:
  - pymdownx.snippets
```

![image](https://github.com/user-attachments/assets/0f6ab95c-23a2-4f49-91e9-abd8b0c6418d)

**Comment by daxartio** [comment]
Hm, I see. Likely, it depends on the priority of the plugin. I’ll try to fix it

**Comment by daxartio** [comment]
I added MKDOCS_GITLAB_PREPROCESSOR_PRIORITY env in v1.4.0. I think it helps you to solve the problem, just to set MKDOCS_GITLAB_PREPROCESSOR_PRIORITY=30
